# data:
#   data_name: 'test'
#   dataset:  # test dataset
#     name: pl
#     path: ./data/crossdocked_pocket10
#     split: ./data/split_by_name.pt

data:
  # name: pl
  # path: /data/DUD-E/raw
  # index_path: /data/DUD-E/
  # data_split_path: 
  # id_split_path: 
  # split_name: 
  # dataset_name: DUD-E

  name: pl
  path: /data/lit_pcba/raw
  index_path: /data/lit_pcba/
  data_split_path: 
  id_split_path: 
  split_name: 
  dataset_name: PCBA

  transform:
    ligand_atom_mode: add_aromatic
    random_rot: False


# model:
#     checkpoint: ./ckpt/pretrained_Pocket2Mol.pt

sample:
  seed: 2020
  mask_init: True
  num_samples: 100
  beam_size: 500
  max_steps: 50
  threshold:
    focal_threshold: 0.5
    pos_threshold: 0.25
    element_threshold: 0.3
    hasatom_threshold: 0.6
    bond_threshold: 0.4